# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Estelle Zheng
name: Estelle Zheng
position: Industrial Ph.D Candidate in Computer Science 
email: estelle.zheng@loria.fr
description: >-
  I am a first year Ph.D candidate in the SYNALP team at [LORIA](https://www.loria.fr/en/) under the supervision of [Christophe Cerisara](https://members.loria.fr/CCerisara/). 
  Prior to LORIA, I received my Master's degree in Applied Mathematics for Data Science from [Institut Polytechnique de Paris](https://www.ip-paris.fr/en).


  My research interests lies in Natural Language Processing (NLP) and more specifically in Large Language Models (LLM). 
  My long-term research goal is to build reliable AI systems to assist and enhance decision-making across various domains.
  
  
  Motivated by this goal, my current research focuses on LLM Agents and a focus on the planning stage.
miscellaneous: >-
  I am an enthusiastic language learner and in my spare time, I do some personal translation of Chinese books to English. I am also a huge fan of Japanese animation and litterature, but also of Korean one!
  I like video games which is the main reason why I do not have a lot of free time.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zhngstl.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: KeunhongP
github_username: zhngstl
#google_scholar: HVZb-5oAAAAJ
#google_analytics: G-MFWSBLRKG0

# Build settings
theme: minima
plugins:
  - jekyll-feed

sass:
  style: compact

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
